-- Nómina Electrónica — agrupación de origen (Maritza / Diana / Externas)
-- Migración 047
--
-- El Excel llevaba tres bloques separados (columnas MARITZA, DIANA, EXTERNAS)
-- y el usuario quiere seguir viendo esa agrupación en la grilla nueva. Es
-- DISTINTA de responsable_id (que sigue pendiente de asignar, ver migración
-- 045): responsable_id es quién presenta la nómina electrónica de esa
-- empresa; origen es solo de qué bloque del Excel venía, para poder agrupar
-- visualmente igual que antes. Texto libre en vez de FK — no referencia nada,
-- es una etiqueta.

ALTER TABLE ne_empresas ADD COLUMN origen VARCHAR(20)
  CHECK (origen IS NULL OR origen IN ('maritza', 'diana', 'externas'));

-- MARITZA (48)
UPDATE ne_empresas SET origen = 'maritza' WHERE name IN (
  'COMPAÑIA DE DANZA VITAL',
  'LA CASONA DE SOFIA',
  'DAYMON COLOMBIA S.A.S',
  'ESSENZA ACCESORIOS S.A.S.',
  'RESTAURANTE ITALIANO PORTONOVO',
  'TISAU MATERIALS SAS',
  'LA ESTAMPERÍA S.A.S',
  'MANGUERAS DEL TUNDAMA',
  'HATO LECHERO HACIENDA PINZON',
  'FRUTIN HELADO ARTESANAL DESDE 1965',
  'TRANSPORTES ELITE',
  'AGENCIA MOBA',
  'ROSAS VILLA ALCIRA',
  'OVINOS EL CAYADO',
  'LATTE CORAZON',
  'DE LA FINCA HUEVOS',
  'SALVITA',
  'INDUSTRIAS SAE',
  'ARANDANOS DE LA FUENTE',
  'ASOCIACION ALEYA',
  'ALBEIRO BECERRA',
  'PORCICOLA GERONIMO',
  'ASOCIACION APICULTURA AL RESCATE',
  'TRAELODEUSA',
  'SUBMERCE',
  'JR AVICOLA ZETAQUIRA',
  'ASOCIACION VILLARTEC',
  'LAVONIA LABS',
  'FRUANTI',
  'ASO. GANADERIA EL PORVENIR',
  'ASO. MUJERES EMPRENDEDORAS',
  'ASO. APICULTORES CARRANGUEROS',
  'SABORES ANCESTRALES',
  'KUNA EXPERIENCES',
  'ESPINOSETAS',
  'HAPS',
  'ASOCIACION AVICOLA CHICAMOCHA',
  'TRADICION DE LOS ABUELOS',
  'PRIATOLI',
  'ASOCIACION BOYAFRUIT',
  'LA ESTACION',
  'CAMSILAC',
  'AMASIJOS DON PABLO SAS',
  'BIOBRASA',
  'AVORAP SAS',
  'INVENTO COLOMBIA',
  'BRULEE REPOSTERIA',
  'CLARO QUE SI'
);

-- DIANA (36)
UPDATE ne_empresas SET origen = 'diana' WHERE name IN (
  'CATACAKES PASTELERIA',
  'ECOVAPOR MULTISERVICIOS',
  'ELIBRY',
  'FINCA AGROPECUARIA SAN RAFAEL',
  'FOUR HILLS TENNIS CLUB',
  'GRANJA AVICOLA PARAISO REAL',
  'HERENCIA PASTRY',
  'LA GALERIA NOBSA',
  'NATURAL ORGANIC PET S.A.S',
  'VETERINARIA TABBY',
  'GANADERIA F.M&L',
  'ELIARCHILA',
  'ALTUZARRA',
  'CAPRO VIVA',
  'THERMOGAN',
  'MIELE DI BOSCO',
  'AVICOLA DOS ALMAS',
  'MAMANKANA',
  'ACHIRAS',
  'DESHIDRATADOS',
  'EL CORRAL DE DANIELA',
  'SEVEN BLESS',
  'ASOCIACION FURA Y TENA',
  'JAIM YAFE',
  'BISTRO CHIA',
  'ASOCIACION AROMATICAS',
  'PLANETA 24/7',
  'ASOCIACION ARTE BOIACA',
  'HERENCIA ANCESTRAL',
  'TY SUASIA',
  'ASOFRESAS',
  'ENTRE NOPALES',
  'ISOMÉTRICO 3D',
  'ESENZA ESPECIAS SAS',
  'PANADERIA Y PASTELERIA ARTESANAL',
  'RUSTIC HOUSE COLOMBIA'
);

-- EXTERNAS (25)
UPDATE ne_empresas SET origen = 'externas' WHERE name IN (
  'ASERCOM',
  'RESTAURANTE DINO',
  'PROYECTO IMPERIO',
  'CORTILINE',
  'SERVIBANDAS',
  'REFUGIO GENESIS',
  'UN MUNDO APICOLA',
  'FE ROOM',
  'SIGEMIN',
  'LACTEOS LAS ROCAS',
  'CONCEPT',
  'FUNDICIONES METALICAS',
  'ERNESTO BECERRA',
  'JOSE MIGUEL',
  'CONSTRUCCIONES',
  'GLOB BERRY',
  'MANFIL',
  'INGEOMESA',
  'GC',
  'CONTROLES',
  'VERTIFEX',
  'SB PUBLICIDAD',
  'SANDRA PATRICIA',
  'TEREMAR',
  'NEBRASKA'
);
