export const SAMPLE_MEMBERS = [
  { id: 'user-1', name: 'María García', email: 'maria@empresa.com', role: 'admin', createdAt: '2026-05-01' },
  { id: 'user-2', name: 'Carlos López', email: 'carlos@empresa.com', role: 'leader', createdAt: '2026-05-01' },
  { id: 'user-3', name: 'Ana Martínez', email: 'ana@empresa.com', role: 'member', createdAt: '2026-05-02' },
  { id: 'user-4', name: 'Pedro Sánchez', email: 'pedro@empresa.com', role: 'member', createdAt: '2026-05-02' },
  { id: 'user-5', name: 'Laura Torres', email: 'laura@empresa.com', role: 'viewer', createdAt: '2026-05-03' },
]

export const SAMPLE_TASKS = [
  {
    id: 'task-1',
    title: 'Diseñar Dashboard',
    description: 'Crear mockup y prototipo del dashboard con estadísticas principales',
    status: 'completed',
    priority: 'high',
    assignedTo: 'user-1',
    dueDate: '2026-05-10',
    createdAt: '2026-05-01',
    updatedAt: '2026-05-10',
  },
  {
    id: 'task-2',
    title: 'Implementar autenticación',
    description: 'Agregar sistema de login con email y contraseña, validación y sesión persistente',
    status: 'in_progress',
    priority: 'high',
    assignedTo: 'user-2',
    dueDate: '2026-05-16',
    createdAt: '2026-05-05',
    updatedAt: '2026-05-12',
  },
  {
    id: 'task-3',
    title: 'Crear módulo de reportes',
    description: 'Generar reportes en PDF con gráficos de rendimiento del equipo',
    status: 'pending',
    priority: 'medium',
    assignedTo: 'user-3',
    dueDate: '2026-05-25',
    createdAt: '2026-05-06',
    updatedAt: '2026-05-06',
  },
  {
    id: 'task-4',
    title: 'Optimizar base de datos',
    description: 'Revisar y optimizar consultas lentas, agregar índices necesarios',
    status: 'pending',
    priority: 'medium',
    assignedTo: 'user-2',
    dueDate: '2026-05-20',
    createdAt: '2026-05-07',
    updatedAt: '2026-05-07',
  },
  {
    id: 'task-5',
    title: 'Actualizar documentación',
    description: 'Documentar endpoints de la API y guías de instalación del proyecto',
    status: 'in_progress',
    priority: 'low',
    assignedTo: 'user-4',
    dueDate: '2026-05-30',
    createdAt: '2026-05-08',
    updatedAt: '2026-05-13',
  },
  {
    id: 'task-6',
    title: 'Testing de integración',
    description: 'Escribir pruebas de integración para todos los módulos principales',
    status: 'pending',
    priority: 'high',
    assignedTo: 'user-1',
    dueDate: '2026-05-17',
    createdAt: '2026-05-09',
    updatedAt: '2026-05-09',
  },
  {
    id: 'task-7',
    title: 'Diseño responsivo mobile',
    description: 'Adaptar todas las vistas para dispositivos móviles y tablets',
    status: 'completed',
    priority: 'medium',
    assignedTo: 'user-3',
    dueDate: '2026-05-12',
    createdAt: '2026-05-04',
    updatedAt: '2026-05-12',
  },
  {
    id: 'task-8',
    title: 'Configurar CI/CD',
    description: 'Configurar pipeline de despliegue automático con GitHub Actions',
    status: 'pending',
    priority: 'low',
    assignedTo: 'user-5',
    dueDate: '2026-06-01',
    createdAt: '2026-05-10',
    updatedAt: '2026-05-10',
  },
]
