export const SAMPLE_MEMBERS = [
  {
    id: 'user-1',
    name: 'María García',
    email: 'maria@empresa.com',
    password: 'admin123',
    role: 'admin',
    groupIds: ['group-1'],
    preferences: { theme: 'light', notifications: true },
    createdAt: '2026-05-01',
  },
  {
    id: 'user-2',
    name: 'Carlos López',
    email: 'carlos@empresa.com',
    password: 'leader123',
    role: 'leader',
    groupIds: ['group-1', 'group-2'],
    preferences: { theme: 'light', notifications: true },
    createdAt: '2026-05-01',
  },
  {
    id: 'user-3',
    name: 'Ana Martínez',
    email: 'ana@empresa.com',
    password: 'member123',
    role: 'member',
    groupIds: ['group-1'],
    preferences: { theme: 'light', notifications: true },
    createdAt: '2026-05-02',
  },
  {
    id: 'user-4',
    name: 'Pedro Sánchez',
    email: 'pedro@empresa.com',
    password: 'member123',
    role: 'member',
    groupIds: ['group-2'],
    preferences: { theme: 'light', notifications: false },
    createdAt: '2026-05-02',
  },
  {
    id: 'user-5',
    name: 'Laura Torres',
    email: 'laura@empresa.com',
    password: 'viewer123',
    role: 'viewer',
    groupIds: ['group-2'],
    preferences: { theme: 'light', notifications: true },
    createdAt: '2026-05-03',
  },
]

const _SAMPLE_TASKS = [
  {
    id: 'task-1',
    title: 'Diseñar Dashboard',
    description: 'Crear mockup y prototipo del dashboard con estadísticas principales',
    status: 'completed',
    priority: 'high',
    assignedTo: ['user-1'],
    dueDate: '2026-05-10',
    groupId: 'group-1',
    tagIds: ['tag-1', 'tag-4'],
    subtasks: [
      { id: 'st-1-1', title: 'Wireframes en papel', completed: true, createdAt: '2026-05-01' },
      { id: 'st-1-2', title: 'Prototipo en Figma', completed: true, createdAt: '2026-05-02' },
    ],
    comments: [],
    createdAt: '2026-05-01',
    updatedAt: '2026-05-10',
  },
  {
    id: 'task-2',
    title: 'Implementar autenticación',
    description: 'Agregar sistema de login con email y contraseña, validación y sesión persistente',
    status: 'in_progress',
    priority: 'high',
    assignedTo: ['user-2'],
    dueDate: '2026-06-16',
    groupId: 'group-2',
    tagIds: ['tag-2', 'tag-3'],
    subtasks: [
      { id: 'st-2-1', title: 'Diseñar AuthContext', completed: true, createdAt: '2026-05-05' },
      { id: 'st-2-2', title: 'Crear LoginForm', completed: false, createdAt: '2026-05-05' },
      { id: 'st-2-3', title: 'Crear ProtectedRoute', completed: false, createdAt: '2026-05-05' },
    ],
    comments: [
      {
        id: 'cmt-2-1',
        authorId: 'user-1',
        text: 'Recuerda validar el token de sesión en cada request.',
        mentions: [],
        createdAt: '2026-05-12T10:30:00.000Z',
        updatedAt: '2026-05-12T10:30:00.000Z',
      },
    ],
    createdAt: '2026-05-05',
    updatedAt: '2026-05-12',
  },
  {
    id: 'task-3',
    title: 'Crear módulo de reportes',
    description: 'Generar reportes en PDF con gráficos de rendimiento del equipo',
    status: 'pending',
    priority: 'medium',
    assignedTo: ['user-3'],
    dueDate: '2026-06-25',
    groupId: 'group-1',
    tagIds: ['tag-1'],
    subtasks: [],
    comments: [],
    createdAt: '2026-05-06',
    updatedAt: '2026-05-06',
  },
  {
    id: 'task-4',
    title: 'Optimizar base de datos',
    description: 'Revisar y optimizar consultas lentas, agregar índices necesarios',
    status: 'pending',
    priority: 'medium',
    assignedTo: ['user-2'],
    dueDate: '2026-06-20',
    groupId: 'group-2',
    tagIds: ['tag-2'],
    subtasks: [],
    comments: [],
    createdAt: '2026-05-07',
    updatedAt: '2026-05-07',
  },
  {
    id: 'task-5',
    title: 'Actualizar documentación',
    description: 'Documentar endpoints de la API y guías de instalación del proyecto',
    status: 'in_progress',
    priority: 'low',
    assignedTo: ['user-4'],
    dueDate: '2026-06-30',
    groupId: 'group-2',
    tagIds: [],
    subtasks: [],
    comments: [],
    createdAt: '2026-05-08',
    updatedAt: '2026-05-13',
  },
  {
    id: 'task-6',
    title: 'Testing de integración',
    description: 'Escribir pruebas de integración para todos los módulos principales',
    status: 'pending',
    priority: 'high',
    assignedTo: ['user-1'],
    dueDate: '2026-06-17',
    groupId: 'group-1',
    tagIds: ['tag-3'],
    subtasks: [],
    comments: [],
    createdAt: '2026-05-09',
    updatedAt: '2026-05-09',
  },
  {
    id: 'task-7',
    title: 'Diseño responsivo mobile',
    description: 'Adaptar todas las vistas para dispositivos móviles y tablets',
    status: 'completed',
    priority: 'medium',
    assignedTo: ['user-3'],
    dueDate: '2026-05-12',
    groupId: 'group-1',
    tagIds: ['tag-1', 'tag-4'],
    subtasks: [],
    comments: [],
    createdAt: '2026-05-04',
    updatedAt: '2026-05-12',
  },
  {
    id: 'task-8',
    title: 'Configurar CI/CD',
    description: 'Configurar pipeline de despliegue automático con GitHub Actions',
    status: 'pending',
    priority: 'low',
    assignedTo: ['user-5'],
    dueDate: '2026-07-01',
    groupId: 'group-2',
    tagIds: ['tag-2'],
    subtasks: [],
    comments: [],
    createdAt: '2026-05-10',
    updatedAt: '2026-05-10',
  },
]
